version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.development
    ports:
      - "3000:3000"
#    command: bash -c "rails server -b 0.0.0.0 -p 3000"
#    volumes:
#      - .:/rails-app-tutorial